name: Keep App Awake

on:
  schedule:
    - cron: "0 */8 * * *" # Runs every 8 hours
  workflow_dispatch:          # Allows you to test it manually

jobs:
  ping-job:
    name: Ping Streamlit App
    runs-on: ubuntu-latest
    steps:
      - name: Send Curl Request
        run: curl -I https://demo-order-dashboard-heinemann.streamlit.app/

  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2