name: Keep App Awake

on:
  schedule:
    - cron: '0 */12 * * *' #12h cycle
  workflow_dispatch: #

jobs:
  keep-awake:
    runs-on: ubuntu-latest
    permissions:
      contents: write # To allow pushing commits
    steps:
      - uses: actions/checkout@v4
      
      - name: Dummy Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit --allow-empty -m "Keep-alive ping (12h cycle)"
          git push